services:
  app:
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:admin@db:5432/locstique
    volumes:
      - .:/app
    command: pnpm start
    restart: always

  db:
    image: postgres:16.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: locstique
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
